# .streamlit/secrets.toml

[general]
questions_sheet_id = "1y0zthY7rLMeAQhjGqwgWcMgUOROvPGp_wy9TZApDbLA"   # 문제 및 모범답안이 있는 시트 ID
criteria_sheet_id = "1nsj6lMNrZ5KrHDHsD6g_b9jxgawN4It1rJQv9RvymgM"          # 채점 기준이 있는 시트 ID

[gcp_service_account]
type = "service_account"
project_id = "YOUR_PROJECT_ID"
private_key_id = "YOUR_PRIVATE_KEY_ID"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
client_email = "YOUR_CLIENT_EMAIL"
client_id = "YOUR_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "YOUR_CLIENT_X509_CERT_URL"

